### PR TITLE
feat(view-available-prducts): Created inventory page

### PR DESCRIPTION
**Pull request by codjoero**
This enables a user to view the product inventory with all details.
login: user
password: andela
@whiz25 @armstrongsouljah @tomuhenry @habatkasa @mariamiah @Emmanuelaaron
[gh-pages](https://codjoero.github.io/Store-Manager-App/)

[Deliveries #161080077]

### CODE REVIEW

**Comment by whiz25** [comment]
@codjoero i like the icons and fonts you have used. However the color choice of black doesn't ryhme with your dark background. You need some thing light, like white for basically the whole page.

**Comment by codjoero** [comment]
@whiz25 Thanks man, let me look into it...tho i was going for a laid back calm theme throughout the site, But maybe i could increase on the alpha of the table list to increase the visibility.

**Comment by whiz25** [comment]
@codjoero yeah sure, just try and see how it will look.

**Comment by codjoero** [comment]
@whiz25 UPDATED the table list background less visible.

**Comment by whiz25** [comment]
@codjoero looks better now

**Comment by codjoero** [comment]
@whiz25 Awesome thanks bro.

**Comment by tomuhenry** [comment]
hey Ronald
Could you share the gh-pages link... Or am I just not seeing it?

**Pull request merged**
