### PR TITLE
161080410 attendant landing page

### PR DESCRIPTION
**Pull request by codjoero**
Hello, this PR allows the user to login and access their dashboard
login: user
password: andela
@armstrongsouljay @tomuhenry @habatkasa @mariamiah @Emmanuelaaron
[gh-pages](https://codjoero.github.io/Store-Manager-App/)
[Deliveries #161080410]

### CODE REVIEW

**Comment by Emmanuelaaron** [comment]
Man this is legit

**Comment by armstrongsouljah** [comment]
Good work on the dashboard. 
I'd suggest you bring down the `font-size` of the app header, also, simulate logout by sending the user back to the login. 
on the dashboard footer, you could get rid of the `margin` around the copy-right and use a larger padding to cover more space. 
##regarding login page
It could do with a little styling suchas the padding around the form and make it more visible since its the entry to your application. 
Try using a span to inform the user when they enter wrong input because when one enters wrong details, nothing happens. 
Otherwise, nice work.

**Comment by codjoero** [comment]
cool thanks, let me look those

**Comment by mariamiah** [comment]
This is very okay

**Comment by habatkasa** [comment]
@codjoero  good work.
though i didnt see how i can log out of the app.
then also the colors yellow and white, dont match. i suggest you choose another back ground color for the accounts link on the dashboard

**Pull request merged**
